# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 07:34
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('link', models.URLField(null=True)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('text', models.TextField(max_length=300)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='')),
                ('comments', models.ManyToManyField(blank=True, to='app.Comment')),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('link', models.URLField(null=True)),
                ('number', models.IntegerField()),
                ('picture', models.ImageField(upload_to='projects/parts')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('picture', models.ImageField(upload_to='projects')),
                ('text', models.TextField()),
                ('author', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('censor', models.BooleanField()),
                ('year', models.CharField(max_length=50)),
                ('translator', models.CharField(max_length=50)),
                ('cleaner', models.CharField(max_length=50)),
                ('corrector', models.CharField(max_length=50)),
                ('typer', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='translation_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Status'),
        ),
    ]
