# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_project_parts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
