# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170316_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='chapters',
            field=models.ManyToManyField(blank=True, to='app.Chapter'),
        ),
    ]
